# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('profile', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, choices=[('President', 'President'), ('Member', 'Member'), ('Executive Director', 'Executive Director'), ('Technical Director', 'Technical Director'), ('Football Manager Operation Department', 'Football Manager Operation Department'), ('CEO', 'CEO'), ('Communications Director', 'Communications Director'), ('Commercial Director', 'Commercial Director'), ('Deputy General Manager-Communication and Public Relations', 'Deputy General Manager-Communication and Public Relations'), ('CFO', 'CFO')], max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
