# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 1, 6, 18, 48, 59, 316535, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
