# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0002_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='about',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='modified',
        ),
    ]
