# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0004_event_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_active',
            new_name='ACTIVATE',
        ),
    ]
