# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0007_auto_20160107_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_content',
            field=models.TextField(blank=True, verbose_name='Event description'),
        ),
    ]
