# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

#        migrations.CreateModel(
#            name='OrganisationalChart',
#            fields=[
#                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                ('first_name', models.CharField(blank=True, max_length=30)),
#                ('last_name', models.CharField(blank=True, max_length=30)),
#                ('position', models.CharField(blank=True, max_length=30)),
#                ('info', models.TextField(blank=True)),
#            ],
#            options={
#                'abstract': False,
#            },
#        ),
        migrations.CreateModel(
            name='CoachingStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('info', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_pts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_pts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stadium', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField()),
                ('time_played', models.CharField(blank=True, max_length=10)),
                ('pts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('two_pa', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('two_pm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('three_pa', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('three_pm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fta', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ftm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tov', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oreb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dreb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ast', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stl', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pf', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AthleticTeamApp.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('info', models.TextField(blank=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('primary_position', models.CharField(blank=True, choices=[(b'PG', b'Point Guard'), (b'SG', b'Shooting Guard'), (b'SF', b'Small Forward'), (b'PF', b'Power Forward'), (b'CE', b'Center')], max_length=2)),
                ('secondary_positions', models.CharField(blank=True, max_length=30)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_arm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('power_body', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('power_legs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_play', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('co_op', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate_of_pos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('two_shots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('three_shots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AthleticTeamApp.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AthleticTeamApp.Team'),
        ),
        migrations.AddField(
            model_name='matchplayerstatistics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AthleticTeamApp.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='AthleticTeamApp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='AthleticTeamApp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='AthleticTeamApp.MatchPlayerStatistics', to='AthleticTeamApp.Player'),
        ),
        migrations.AddField(
            model_name='coachingstaffmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AthleticTeamApp.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together=set([('player', 'owner')]),
        ),
    ]
