# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AthleticTeamApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingStaffMember2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('info', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),

        migrations.AddField(
            model_name='CoachingStaffMember2',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AthleticTeamApp.Team'),
        ),
    ]
