# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AthleticTeamApp', '0002_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingstaffmember',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='coachingstaffmember',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coachingstaffmember',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_pts',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_away',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_pts',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='ast',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='blk',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='dreb',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='fta',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='ftm',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='oreb',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='pf',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='pts',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='stl',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='three_pa',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='three_pm',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='time_played',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='tov',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='two_pa',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchplayerstatistics',
            name='two_pm',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(null=True, max_digits=3, decimal_places=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(max_length=2, choices=[(b'PG', b'Point Guard'), (b'SG', b'Shooting Guard'), (b'SF', b'Small Forward'), (b'PF', b'Power Forward'), (b'CE', b'Center')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='secondary_positions',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=30),
        ),
    ]
