# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('AthleticTeamApp', '0002_coachingstaffmember2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachingStaffMember2',
            new_name='OrganisationalChart',
        ),
    ]
