# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AthleticTeamApp', '0003_auto_20151220_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationalchart',
            name='area',
            field=models.CharField(blank=True, choices=[(b'ASM', b'Area Sports Management'), (b'AGM', b'Area General Management')], max_length=2),
        ),
    ]
