# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AthleticTeamApp', '0004_organisationalchart_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationalchart',
            name='area',
        ),
        migrations.AlterField(
            model_name='organisationalchart',
            name='position',
            field=models.CharField(blank=True, choices=[(b'PG', b'Point Guard'), (b'SG', b'Shooting Guard'), (b'SF', b'Small Forward'), (b'PF', b'Power Forward'), (b'CE', b'Center')], max_length=4),
        ),
    ]
