# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AthleticTeamApp', '0007_auto_20151220_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationalchart',
            name='position',
            field=models.CharField(blank=True, choices=[(b'Stadium Operation Manager', b'Sports Organizational Manager'), (b'Youth Department Techincal Manager', b'Youth Department Techincal Manager'), (b'Youth Department Organization Manager', b'Youth Department Organization Manager'), (b'Sports Communications Manager', b'Sports Communications Manager'), (b'Team Manager', b'Team Manager'), (b'Technical Secretariat', b'Technical Secretariat'), (b'General Operations & Special Projects Manager', b'General Operations & Special Projects Manager'), (b'Developement & Stadium Operation Manager', b'Developement & Stadium Operation Manager'), (b'Commercial Manager', b'Commercial Manager'), (b'Institutional Communication Manager', b'Institutional Communication Manager'), (b'Facilities & General Services Director', b'Facilities & General Services Director'), (b'Security Manager', b'Security Manager'), (b'Stadium Operation Manager', b'Stadium Operation Manager'), (b'Sponsorship & Sales Manager', b'Sponsorship & Sales Manager')], max_length=50),
        ),
    ]
