# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AthleticTeamApp', '0008_auto_20151221_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationalchart',
            name='team',
        ),
    ]
